# Generated by Django 3.0.4 on 2020-03-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_main', '0002_auto_20200313_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='lat',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='lon',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
