# Generated by Django 3.0.4 on 2020-03-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_main', '0003_auto_20200313_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='division',
            name='lon',
        ),
        migrations.AddField(
            model_name='district',
            name='lat',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='lon',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
