# Generated by Django 3.0.4 on 2020-03-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_main', '0004_auto_20200313_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chandakatha',
            name='bn_name',
        ),
        migrations.RemoveField(
            model_name='chandakatha',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chandakatha',
            name='url',
        ),
    ]
