# Generated by Django 3.0.4 on 2020-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_main', '0005_auto_20200316_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='chandakatha',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
